---
title: "R Notebook"
# output: html_notebook
---


```{r}

library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(RColorBrewer)
library(stringr)
library(ComplexHeatmap)
library(varhandle)
library(ggpubr)
library(viper)
library(harmony)
set.seed(777)
options(ggrepel.max.overlaps = Inf)


###
dir<-"Rutilities_v0.1"
files = list.files(path=dir, full.names = TRUE)
sapply(files, source) %>% invisible()


###
dir<-"Rosa_v0.7"
files = list.files(path=dir, full.names = TRUE)
sapply(files, source) %>% invisible()


```




```{r}

library(RColorBrewer)

n <- 60

qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]

col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

library(scales)

show_col(col_vector)

# order, PR, HC, BC, AC, SAC, RGC, MG

cols<-c("#FF7F00", "#FDB462", "#F0027F", "#377EB8", "#BEAED4", "#7FC97F", "#666666")

```



```{r}

load("macaque.regul.samples.rda")

regul<-regul.samples
regul<-lapply(regul, FUN=pruneRegulon, cutoff=50, adaptive=FALSE, eliminate=FALSE)
names(regul) -> samples
regul


load("seu.integrated.M3.LabelTransfered.CellAssignedAtClusterLevel.rda")

DefaultAssay(seu)<-"RNA"

seu[['SCT']]<-NULL

Idents(seu)<-"orig.ident"

#
VlnPlot(seu, features="nCount_RNA")


```


BUG 

```{r}

Idents(seu)<-"orig.ident"
seu.list<-SplitObject(seu, split.by="orig.ident")
seu.list


seu.list<-lapply(seu.list, FUN = function(x){
  
                                   signature.wt.method="rank"
  
  seu<-SCTransform(x, 
                   method="glmGamPoi", 
                   vst.flavor="v1",
                   return.only.var.genes = FALSE)
  
  
  eset<-seu@assays$SCT@scale.data %>% as.matrix()
  
  
  eset<-AdjustSignatureMatrix(eset, n_bins=100)
  
  summary(as.vector(eset))
  
  
  
  pa<-MetaRosa(eset=eset,
               regulon.list=regul,
               reg_weight="both",
               reg_weight_combination="multiplicative",
               wt.features= NULL,
               DoScaleEset = FALSE,
               minsize=20,
               integration.method="average")
  
  #
  
  pa<-pa%>% as.matrix()%>% as.data.frame() %>% drop_na() %>% as.matrix()
  
  pa<-round(pa, digits=2)
  
  seu<-AddActivityAssay(seu, activity.matrix=pa)
  
  return(seu)
  
})
```


```{r}

seu.list

seu<-merge(x=seu.list$M3Fovea1, y=c(seu.list$M3Fovea2, seu.list$M3Fovea3))


seu@meta.data$sample<-seu@meta.data$orig.ident

seu@meta.data$class<-seu@meta.data$Class


seu

message("The protein activity matrix is generated")

n.features<-700
tmp.sd<-apply(as.matrix(seu@assays$Activity@data), 1, sd)
tmp.sd<-sort(tmp.sd, decreasing=TRUE)
features<-names(tmp.sd[1:n.features])

seu@assays$Activity@scale.data<-seu@assays$Activity@data
#
seu <- RunPCA(seu, features = features)
seu<-RunHarmony(seu, group.by.vars="sample")

seu <- RunUMAP(seu, reduction="harmony", dims = 1:50)


#----------
p1<-DimPlot(seu, reduction = "umap", group.by="class")
p1

p2<-DimPlot(seu, reduction = "umap", group.by="sample")
p2


seu <- FindNeighbors(seu, reduction="harmony",  dims = 1:50)
seu <- FindClusters(seu, reduction="harmony", resolution = 0.5)


# reduction<-"umap"
#

p1+p2

ggsave("Clustering_umap_clusters_viperDistance.pdf", width=17, height = 5)


p1
ggsave("Clustering_umap_vp_clusters.pdf", width=6.5, height = 5)


p2
ggsave("Clustering_umap_class.pdf", width=6, height = 5)


#----------------------------
# Change the colors
#----------------------------

reduction<-"umap"


cols<-c("#FF7F00", "#FDB462", "#F0027F", "#377EB8", "#BEAED4", "#7FC97F", "#666666")

seu@meta.data$class %>% table()

seu@meta.data$class<-factor(seu@meta.data$class, levels=c("Cone", "Rod", "HC", "BC", "AC", "RGC", "MG"))

seu@meta.data$class

Idents(seu)<-"class"

p2<-DimPlot(seu, 
            reduction=reduction,
            group.by='class',
            cols=cols,
            label = TRUE, repel = TRUE)


#--------------
p2
p2<-p2+gg.theme
p2

ggsave("Clustering_umap_class.pdf", width=5.5, height = 5)
ggsave("Clustering_umap_class.eps", width=5.5, height = 5)


#---------------
cols<-c("grey", "blue", "green4")
p3<-DimPlot(seu, 
            reduction=reduction,group.by='sample', 
            cols= cols,
            label = FALSE, 
            repel = TRUE)
p3<-p3+gg.theme3
p3

ggsave("Clustering_umap_sample.pdf", width=6, height = 5)



```



```{r}
#
seu@meta.data$cell_type_v2<-seu@meta.data$class %>% as.character()
seu@meta.data$cell_type_v2[seu@meta.data$cell_type_v2 =="Cone"]<-"PR"
seu@meta.data$cell_type_v2[seu@meta.data$cell_type_v2 =="Rod"]<-"PR"

DimPlot(seu, group.by = "cell_type_v2")

```



```{r}


seu@meta.data$cell_typ_v2<-factor(seu@meta.data$cell_type_v2, levels=c("PR","HC", "BC", "AC", "RGC", "MG"))

Idents(seu)<-"cell_type_v2"

cols<-c("#FF7F00", "#F0027F", "#377EB8", "#BEAED4", "#7FC97F", "#666666")



p1<-DimPlot(seu, 
            reduction = "umap", 
            group.by = "cell_type_v2", 
            cols=cols,
            label = TRUE,
            repel=TRUE)+NoLegend()

p1

p1<-p1+gg.theme+labs(title="")
p1

ggsave(file="umap_macaque.pa.pdf", width=5, height=5)

```



Do differential activity analysis

```{r}


Idents(seu)<-"cell_type_v2"


DefaultAssay(seu)<-"Activity"


markers.pa.test<-DoActivityMarkerTest(seu, 
                               group.by="cell_type_v2",
                               assay="Activity",
                               slot="data",
                               test="t.test"
                               )

markers.pa.test

markers<-markers.pa.test



tmp<-grep("^MSTR|^LOC", markers$gene)

if(length(tmp)>0){
  markers<-markers[-tmp,]   
}


tmp<-grep("^MT-|RP[SL][[:digit:]]", markers$gene)

if(length(tmp)>0){
  markers<-markers[-tmp,] 
}


```



```{r}

markers$cluster<-factor(markers$cluster, levels=c("PR","HC", "BC", "AC", "RGC", "MG"))

top.n<-7

top<-markers %>%
  arrange(desc(mean_diff)) %>%
   distinct(gene, .keep_all = TRUE) %>%
  as.data.frame() %>%
  group_by(cluster) %>%
  slice_head(n = top.n)

top %>% print(n=100)


top<-markers %>%
  group_by(cluster) %>%
  slice_head(n = top.n)

top %>% print(n=100)



seu.sub<-subset(seu, downsample=200)


p<-DoHeatmap(seu.sub, 
          features = top$gene,
          group.colors = cols,
          slot="scale.data",
          assay = "Activity",
          disp.min = -10,
          disp.max=10,
          angle=270
          )

p


#---------

p<-p+ scale_fill_gradient2(low="grey", mid="white", high="orange") 
p<-p+labs(fill = "Activity") 
p

ggsave(file="pa.markers.pa.pdf", width=3.5, height=5)

# 
p<-DoHeatmap(seu.sub, 
          features = top$gene,
          group.colors = cols,
          assay="SCT",
          slot="data",
          #disp.min = -10,
          #disp.max=10,
          angle=270
          )

p



p<-p+ scale_fill_gradient2(low="grey", mid="white", high="red") 
p

ggsave(file="pa.markers.exp.pdf", width=3.5, height=5)


```

```{r}
save(seu, file="seu.macaque.pa.rda")
```


```{r}
sessionInfo()
```


