---
title: "R Notebook"
# output: html_notebook
---


```{r}

rm(list=ls())
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(RColorBrewer)
library(stringr)
library(ComplexHeatmap)
library(varhandle)
library(viper)


set.seed(777)
options(ggrepel.max.overlaps = Inf)


dir<-"Rutilities_v0.1"
files = list.files(path=dir, full.names = TRUE)
sapply(files, source) %>% invisible()

dir<-"Rosa_v0.7"
files = list.files(path=dir, full.names = TRUE)
files

invisible(sapply(files, source))

```






Load the regulon 
```{r}
getwd()

load("regul.samples.rda")
samples<-names(regul.samples)
regul.list.pruned<-lapply(regul.samples, FUN=pruneRegulon, cutoff=50, adaptive=FALSE, eliminate=FALSE)


```


Load the data 
```{r}

load("seu.s10.reannotated.v2.rda")

#
seu@meta.data$cell_type_v2<-seu@meta.data$cell_type_v2 %>% as.character()
seu@meta.data$cell_type_v2[seu@meta.data$cell_type_v2 =="Cone"]<-"PR"

Idents(seu)<-"cell_type_v2"

seu<-subset(seu, idents=c("PR", "AC", "BC", "HC", "RGC", "MG"))

#

seu@meta.data$orig.ident %>% table()
Idents(seu)<-"orig.ident"

```

Infer PA for each sample
```{r}

Idents(seu)<-"orig.ident"

Idents(seu)<-"cell_type"

seu@meta.data$orig.ident %>%  unique() %>% sort()
seu <- SCTransform(seu, method = "glmGamPoi", return.only.var.genes = FALSE)

variance.residual<-seu@assays$SCT@SCTModel.list$model1@feature.attributes$residual_variance
names(variance.residual)<-rownames(seu)

wt.feature<- sort(variance.residual, decreasing=TRUE)


wt.feature[1:100]

eset<-seu@assays$SCT@scale.data %>% as.matrix() 

eset<-AdjustSignatureMatrix(eset, n_bins=100)

summary(as.vector(eset))


```



```{r}
#
pa<-Rosa(eset=eset,
             regulon=regul.list.pruned$mouse_acs10,
              reg_weight="both",
              reg_weight_combination="multiplicative",
             wt.features= NULL)

# 
pa<-pa  %>% as.data.frame() %>% drop_na() %>% as.matrix()
pa<-round(pa, digits=2)


pa[1:10,1:10]

summary(as.vector(pa))

seu<-AddActivityAssay(seu, activity.matrix=pa)


```


#
```{r}

seu@assays$Activity@scale.data<-t(scale(t(seu@assays$Activity@data)))

# Get the highly variable TFs
pa<-seu@assays$Activity@data
sd<-apply(pa, 1, sd)
sd<-sort(sd, decreasing=TRUE)
hvf<-sd[1:700] %>% names()

# do clustering 
DefaultAssay(seu)<-"Activity"
seu<-RunPCA(seu, assay="Activity", features=hvf)
seu<-RunUMAP(seu, dims=1:20)
seu<-FindNeighbors(seu, dims=1:20)
seu<-FindClusters(seu)
DimPlot(seu, reduction="umap",group.by="cell_type_v2", label=TRUE)

```




Load custome-written functions
```{r}

dir<-"/Users/mumu/Documents/bioSoft/bioSoft/Rpackages/scML/Rutilities_v0.1_20240321"
files = list.files(path=dir, full.names = TRUE)
files
sapply(files, source)


```


Save the figure
```{r}

seu@meta.data$cell_typ_v2<-factor(seu@meta.data$cell_type_v2, levels=c("PR","HC", "BC", "AC", "RGC", "MG"))

Idents(seu)<-"cell_type_v2"

# cols<-c("#FF7F00", "#F0027F", "#377EB8", "#BEAED4", "#BEBAD1", "#7FC97F", "#666666")
cols<-c("#BEAED4","#377EB8","#F0027F", "#666666", "#FF7F00",   "#7FC97F")



p1<-DimPlot(seu, 
            reduction = "umap", 
            group.by = "cell_type_v2", 
            cols=cols,
            label = TRUE,
            repel=TRUE)+NoLegend()

p1

p1<-p1+gg.theme+labs(title="")
p1

ggsave("cell.type.pa.celltypev2.pdf", width=5, height=5)

```



Do differential activity analysis
```{r}

Idents(seu)<-"cell_type_v2"
  

markers<-DoActivityMarkerTest(seu, 
                               group.by="cell_type_v2",
                               assay="Activity",
                               slot="data",
                               test="t.test"
                               )

markers


tmp<-grep("^MSTR|^LOC", markers$gene)

if(length(tmp)>0){
  
  markers<-markers[-tmp,]  
  
}



tmp<-grep("^MT-|RP[SL][[:digit:]]", markers$gene)



if(length(tmp)>0){
  
  markers<-markers[-tmp,] 
  
}



```


```{r}

markers$cluster<-factor(markers$cluster, levels=c("PR","HC", "BC", "AC", "RGC", "MG"))

top.n<-10

top<-markers %>%
  arrange(desc(mean_diff)) %>%
   distinct(gene, .keep_all = TRUE) %>%
     arrange(cluster) %>%
  as.data.frame() %>%
  group_by(cluster) %>%
  slice_head(n = top.n)

top %>% print(n=100)


seu@meta.data$cell_type_v2<-factor(seu@meta.data$cell_type_v2, levels=c("PR", "HC", "BC", "AC", "RGC", "MG"))

Idents(seu)<-"cell_type_v2"

seu.sub<-subset(seu, downsample=200)

cols<-c("#FF7F00", "#F0027F", "#377EB8", "#BEAED4", "#7FC97F", "#666666")

p<-DoHeatmap(seu.sub, 
          features = top$gene,
          group.colors = cols,
          slot="data",
          disp.min = -10,
          disp.max=10,
          angle=270
          )

p

#---------

p<-p+ scale_fill_gradient2(low="grey", mid="white", high="red2") 
p<-p+labs(fill = "Activity") 
p

ggsave(file="pa.markers.pa.pdf", width=4, height=7)

# 
p<-DoHeatmap(seu.sub, 
          features = top$gene,
          group.colors = cols,
          assay="SCT",
          slot="data",
          angle=270
          )

p

#---------

p<-p+ scale_fill_gradient2(low="grey", mid="white", high="red2") 
p

ggsave(file="pa.markers.exp.pdf", width=4, height=7)


```



```{r}
save(seu, file="seu.mouse.pa.rda")
```


The end
```{r}
sessionInfo()
```


