---
title: "R Notebook"
#output: html_notebook
---


```{r}
rm(list=ls())
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(RColorBrewer)
library(stringr)
library(ComplexHeatmap)
library(varhandle)
library(viper)

set.seed(777)
options(ggrepel.max.overlaps = Inf)
```


Load custome-written functions
```{r}
dir<-"Rutilities_v0.1"
files = list.files(path=dir, full.names = TRUE)
sapply(files, source) %>% invisible()
```


```{r}
dir<-"Rosa_v0.7"
files = list.files(path=dir, full.names = TRUE)
sapply(files, source) %>% invisible()
```


Load the regulon 
```{r}

load("regul.samples.lamprey.rda")

regul<-regul.samples
regul<-lapply(regul, FUN=pruneRegulon, cutoff=50, adaptive=FALSE, eliminate=FALSE)
names(regul) -> samples
regul

samples<-names(regul.samples)
regul.list.pruned<-lapply(regul.samples, FUN=pruneRegulon, cutoff=50, adaptive=FALSE, eliminate=FALSE)
```


Load the data 
```{r}

load("seu.lamprey.all.class.rda")

DefaultAssay(seu)<-"RNA"
seu[['SCT']]<-NULL
Idents(seu)<-"orig.ident"

#
VlnPlot(seu, features="nCount_RNA")
```


```{r}
DimPlot(seu, group.by = "class")
```


Remove SAC 
```{r}

Idents(seu)<-"class"
seu<-subset(seu, idents="SAC", invert=TRUE)

```


```{r}
#
seu@meta.data$cell_type_v2<-seu@meta.data$class %>% as.character()


Idents(seu)<-"cell_type_v2"

#
seu@meta.data$orig.ident %>% table()
Idents(seu)<-"orig.ident"
seu.0<-seu
Idents(seu.0)<-"orig.ident"

```

Infer PA for each sample
```{r}

Idents(seu)<-"orig.ident"

seu@meta.data$orig.ident %>%  unique() %>% sort()
seu <- SCTransform(seu, method = "glmGamPoi", return.only.var.genes = FALSE)

eset<-seu@assays$SCT@scale.data %>% as.matrix() 

eset<-AdjustSignatureMatrix(eset, n_bins=100)
summary(as.vector(eset))
```



```{r}
#
summary(as.vector(eset))

  pa<-MetaRosa(eset=eset,
               regulon.list=regul,
               reg_weight="both",
               reg_weight_combination="multiplicative",
               wt.features= NULL,
               DoScaleEset = FALSE,
               minsize=20,
               integration.method="average")
  
  pa<-pa%>% as.matrix()%>% as.data.frame() %>% drop_na() %>% as.matrix()
  
  pa<-round(pa, digits=2)
  
  seu<-AddActivityAssay(seu, activity.matrix=pa)
```



```{r}
pa<-seu@assays$Activity@data
seu@assays$Activity@scale.data<-t(scale(t(pa)))

sd<-apply(pa, 1, sd)
sd<-sort(sd, decreasing=TRUE)
hvf<-sd[1:700] %>% names()


DefaultAssay(seu)<-"Activity"
seu<-RunPCA(seu, assay="Activity", features=hvf)
seu<-RunUMAP(seu, dims=1:50)
seu<-FindNeighbors(seu, dims=1:50)
seu<-FindClusters(seu)
DimPlot(seu, reduction="umap",group.by="cell_type_v2", label=TRUE)
DimPlot(seu, reduction="umap",group.by="class", label=TRUE)
```

```{r}

seu@meta.data$cell_type_v2<-factor(seu@meta.data$cell_type_v2, levels=c("PR","HC", "BC", "AC", "RGC", "MG"))
Idents(seu)<-"cell_type_v2"

# cols<-c("#FF7F00", "#F0027F", "#377EB8", "#BEAED4", "#BEBAD1", "#7FC97F", "#666666")
cols<-c("#FF7F00", "#F0027F", "#377EB8", "#BEAED4", "#7FC97F", "#666666")

p1<-DimPlot(seu, 
            reduction = "umap", 
            group.by = "cell_type_v2", 
            cols=cols,
            label = TRUE,
            repel=TRUE)+NoLegend()

p1

p1<-p1+gg.theme+labs(title="")
p1

ggsave("cell.type.pa.pdf", width=7, height=7)
```



Do differential activity analysis
```{r}

Idents(seu)<-"cell_type_v2"

DefaultAssay(seu)<-"Activity"


markers<-DoActivityMarkerTest(seu, 
                               group.by="cell_type_v2",
                               assay="Activity",
                               slot="data",
                               test="t.test"
                               )

markers


tmp<-grep("^MSTR|^LOC", markers$gene)

if(length(tmp)>0){
  markers<-markers[-tmp,]   
}



tmp<-grep("^MT-|RP[SL][[:digit:]]", markers$gene)

if(length(tmp)>0){
  markers<-markers[-tmp,] 
}

markers
```



```{r}

markers <- markers %>%
  filter(mean_diff>1) %>%
  filter(p_value_fdr<0.01) %>%
  ungroup() %>%
  arrange(desc(mean_diff)) %>%
  distinct(gene, .keep_all = TRUE) %>%
  as.data.frame() %>%
  group_by(cluster) %>%
  arrange(cluster)

markers


#
markers_summary <- markers %>%
  summarize(number_of_members = n()) %>%
  arrange(cluster)

# Print or view the summary
print(markers_summary)
```


DEBUG
```{r}

Idents(seu)<-"orig.ident"

seu<-subset(seu, idents="s10")

markers$cluster<-factor(markers$cluster, levels=c("PR","HC", "BC", "AC", "RGC", "MG"))

top.n<-7

top<-markers %>%
  arrange(desc(mean_diff)) %>%
   distinct(gene, .keep_all = TRUE) %>%
     arrange(cluster) %>%
  as.data.frame() %>%
  group_by(cluster) %>%
  slice_head(n = top.n)

top %>% print(n=100)

Idents(seu)<-"cell_type_v2"

seu.sub<-subset(seu, downsample=200)

Idents(seu.sub)<-"cell_type_v2"

cols<-c("#FF7F00", "#F0027F", "#377EB8", "#BEAED4", "#7FC97F", "#666666")

p<-DoHeatmap(seu.sub, 
          features = top$gene,
          group.colors = cols,
          label=TRUE,
          slot="data",
          assay = "Activity",
          disp.min = -10,
          disp.max=10,
          angle=270
          )

p

#---------
p<-p+ scale_fill_gradient2(low ="grey", mid = "white", high = "orange")

p<-p+labs(fill = "Activity") 
p

ggsave(file="pa.markers.pa.pdf", width=3.5, height=5)


```


Save the data
```{r}
save(seu, file="seu.lamprey.pa.rda")

```



The END
```{r}
sessionInfo()
```


